### ISSUE TITLE
conection and use of the input data

### ISSUE THREAD

**Issue by Crisgo11** [jasmineRepo/LabourForceParticipation#2]
Hello!
could you please explain me how works the loading of the input data in the microsimulation, becasue I don't see in any part of the code where is the lecture of the input data, I just see the file input.h2, but not how is the conection of these data with any class.
thanks a lot

**Comment by rer98** [comment]
Hi Crisgo11,

The input.h2.db file contains a database table called 'person' that contains all the input data of the initial population.  The person table is loaded in the buildObjects method of the LabourParticipationModel class on line 133 with the command:

List<Person> initialPopulation = (List<Person>) DatabaseUtils.loadTable(Person.class);

For more information on using JAS-mine, please see the documentation at http://www.jas-mine.net/home/documentation.

Best wishes,

Ross

**Comment by Crisgo11** [comment]
Dear professor,
thanks for the info I'm very grateful.
I'm exploring all the microsimulation platform to learn how to make my own
microsimulation.

best regards
